version: 2
jobs:
  build_and_test_elixir:
    docker:
      - image: circleci/elixir:1.7.1
      - image: circleci/postgres:10.3

    environment:
      MIX_ENV: test
      COVERALLS_REPO_TOKEN: WQJAD2rl0QMcK0OukyWM49Aq1gXqQEJXY

    working_directory: /home/circleci/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - elixir-build-v3-{{ checksum "mix.lock" }}
      - run:
          name: "Install Hex"
          command: mix local.hex --force
      - run:
          name: "Install Rebar"
          command: mix local.rebar --force
      - run:
          name: "Install Elixir dependencies"
          command: mix deps.get
      - run:
          name: "Compile Elixir source"
          command: mix compile
      - run:
          name: "Create the test database"
          command: mix ecto.create
      - run:
          name: "Run Elixir test suite (with coveralls)"
          command: mix coveralls
      - run:
          name: "Run Elixir linting"
          command: mix credo
      - run:
          name: "Run Elixir formatter check"
          command: mix format --check-formatted
      - run:
          name: "Run dialyzer"
          command: mix dialyzer
      - save_cache:
          key: elixir-build-v3-{{ checksum "mix.lock" }}
          paths:
            - '_build'
            - 'deps'
            - '~/.mix'

  build_and_test_elm:
    docker:
      - image: circleci/node:8

    working_directory: /home/circleci/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - elm-stuff-v7-{{ checksum "assets/package.json" }}-{{ checksum "assets/elm/elm.json" }}
      - restore_cache:
          keys:
            - elixir-build-v3-{{ checksum "mix.lock" }}
      - run:
          name: "Install yarn packages"
          command: cd assets && yarn install
      - run:
          name: "Run Elm test suite"
          command: script/elm-test
      - save_cache:
          key: elm-stuff-v7-{{ checksum "assets/package.json" }}-{{ checksum "assets/elm/elm.json" }}
          paths:
            - '~/.elm'
            - 'assets/elm/elm-stuff'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_elixir
      - build_and_test_elm:
          requires:
            - build_and_test_elixir
